name: storage-benchmarking
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9.2
  - pytorch=1.9.0
  - pip=21.2.4
  - pip:
      - numpy==1.21.1
      - pillow==8.3.1
      - torchaudio==0.9.0
      - torchtext==0.10.0
      - torchvision==0.10.0
      - tqdm==4.61.2
      - pre-commit==2.13.0
      - matplotlib==3.4.3
      - pandas==1.3.2
      - overrides==6.1.0
      - h5py==3.4.0
      - s3fs==2021.8.1
      - pytest==6.2.5
      - boto3
      - jupyter==1.0.0
      - humanize==3.11.0
      - pytorch_lightning==1.4.7
